name: C/C++ CI

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwayland-dev \
          wayland-protocols \
          libcairo2-dev \
          libpango1.0-dev \
          libxkbcommon-dev
    - name: make
      run: make
